name: changelog_cmd
description: Command-line application to manage in the correct way the git metadata to build the changelog.
version: 0.0.1-beta.4
homepage: https://github.com/vincenzopalazzo/changelog.dart/tree/main/packages/changelog-cmd

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  args: ^2.3.0
  octokit: ^0.0.3
  gql: ^0.13.0
  changelog_lib: ^0.0.1-beta.3
  json_annotation:
  json_serializable: 
  graphql: ^5.1.1
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.7
  graphql_codegen: ^0.9.0
  lints: ^1.0.0