name: changelog_lib
description: build your changelog extractor in a fashion way.
version: 0.0.1-beta.3
homepage: https://github.com/vincenzopalazzo/changelog.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
