name: changelog-lib build binary

on:
  release:
    types: [created]
  workflow_run:
    workflows:
      - "changelog.dart sanity code base"
      - "changelog.dar test"
    branches: [ main ]
    types:
      - completed

jobs:
  build_changelog_cmd:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        include:
          - os: ubuntu-latest
            output-name: linux
          - os: macOS-latest
            output-name: osx
          - os: windows-latest
            output-name: windows.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: make dep
      - run: mkdir packages/changelog-cmd/build
      - run: make build OS=${{ matrix.output-name }}
      - uses: actions/upload-artifact@v1
        with:
          name: changelog-cmd
          path: packages/changelog-cmd/build
